spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  flyway:
    enabled: true
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceName: ReplicaDbScheduler
      org.quartz.threadPool.threadCount: 2
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 30m
server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
replicadb:
  server:
    execution:
      pool-size: 4
    local-execution:
      enabled: true
