server:
  port: 8080
spring:
  application:
    name: replicadb-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: health
replicadb:
  server:
    execution:
      pool-size: 4
    audit:
      retention-days: 365
