server:
  port: 8080
spring:
  application:
    name: replicadb-server
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceName: ReplicaDbScheduler
      org.quartz.threadPool.threadCount: 2
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: health
replicadb:
  server:
    execution:
      pool-size: 4
    audit:
      retention-days: 365
