package org.replicadb.server.audit.domain;

public enum AuditAction {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_PASSWORD_CHANGED,
    JOB_CREATED,
    JOB_UPDATED,
    JOB_PERMISSION_REPLACED,
    JOB_PERMISSION_REVOKED,
    JOB_SCHEDULE_UPSERTED,
    JOB_SCHEDULE_DELETED,
    RUN_TRIGGERED,
    RUN_CANCEL_REQUESTED,
    RUN_RETRIED,
    RUN_SUCCEEDED,
    RUN_FAILED,
    RUN_CANCELLED
}
