create table if not exists public.t_sink (
    c_smallserial smallserial,
    c_serial serial,
    c_bigserial bigserial,
    c_smallint smallint,
    c_integer integer,
    c_bigint bigint,
    c_decimal decimal,
    c_numeric numeric,
    c_real real,
    c_double double	precision,
    c_money money,
    c_varchar varchar(10),
    c_char char(2),
    c_text text,
    c_bytea bytea,
    c_date date,
    c_timestamp timestamp,
    c_timestamptz timestamp with time zone,
    c_time time,
    c_timetz time with time zone,
    c_boolean boolean,
    c_point point,
    c_line line,
    c_lseg lseg,
    c_box box,
    c_path path,
    c_polygon polygon,
    c_circle circle,
    c_xml xml,
    c_json json,
    c_jsonb jsonb,
    c_array integer[],
    c_array2 text[][],
    "for" text,
    PRIMARY KEY (c_serial)
);