package org.replicadb.manager;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.replicadb.cli.ToolOptions;

import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for SqlManager staging table safeguards.
 * Tests focus on dropStagingTable() method's protection against dropping user-defined tables.
 * Uses PostgresqlManager as a concrete implementation for testing SqlManager behavior.
 */
class SqlManagerStagingTableTest {
    private static final Logger LOG = LogManager.getLogger(SqlManagerStagingTableTest.class);
    
    private Connection mockConnection;
    private Statement mockStatement;
    
    @BeforeEach
    void setUp() {
        mockConnection = mock(Connection.class);
        mockStatement = mock(Statement.class);
        
        try {
            when(mockConnection.createStatement()).thenReturn(mockStatement);
            when(mockStatement.executeUpdate(anyString())).thenReturn(1);
        } catch (SQLException e) {
            fail("Mock setup failed: " + e.getMessage());
        }
    }
    
    /**
     * Test helper to create a manager with mocked connection.
     */
    private PostgresqlManager createManagerWithMockConnection(String[] args) throws Exception {
        ToolOptions options = new ToolOptions(args);
        return new PostgresqlManager(options, DataSourceType.SINK) {
            @Override
            public Connection getConnection() {
                return mockConnection;
            }
        };
    }

    @Test
    void testDropStagingTable_userDefinedTable_shouldSkipDrop() throws Exception {
        // Given: User explicitly defined staging table
        String[] args = {
            "--source-connect", "jdbc:postgresql://localhost:5432/test",
            "--source-table", "source_table",
            "--sink-connect", "jdbc:postgresql://localhost:5432/test",
            "--sink-table", "sink_table",
            "--sink-staging-table", "my_custom_staging_table",  // User-defined!
            "--mode", "incremental"
        };
        
        PostgresqlManager manager = createManagerWithMockConnection(args);
        
        // When: dropStagingTable is called
        manager.dropStagingTable();
        
        // Then: DROP statement should NOT be executed
        verify(mockStatement, never()).executeUpdate(anyString());
        verify(mockConnection, never()).commit();
        
        LOG.info("✓ User-defined staging table was correctly preserved");
    }

    @Test
    void testDropStagingTable_autoGeneratedTable_shouldDrop() throws Exception {
        // Given: No user-defined staging table (will be auto-generated)
        String[] args = {
            "--source-connect", "jdbc:postgresql://localhost:5432/test",
            "--source-table", "source_table",
            "--sink-connect", "jdbc:postgresql://localhost:5432/test",
            "--sink-table", "sink_table",
            "--sink-staging-schema", "public",
            "--mode", "incremental"
            // NOTE: No --sink-staging-table specified, so it's auto-generated
        };
        
        PostgresqlManager manager = createManagerWithMockConnection(args);
        
        // When: dropStagingTable is called
        manager.dropStagingTable();
        
        // Then: DROP statement SHOULD be executed
        verify(mockStatement, times(1)).executeUpdate(contains("DROP TABLE"));
        verify(mockStatement, times(1)).close();
        verify(mockConnection, times(1)).commit();
        
        LOG.info("✓ Auto-generated staging table was correctly dropped");
    }

    @Test
    void testDropStagingTable_emptyUserDefinedTable_shouldDrop() throws Exception {
        // Given: Empty string for staging table (treated as auto-generated)
        String[] args = {
            "--source-connect", "jdbc:postgresql://localhost:5432/test",
            "--source-table", "source_table",
            "--sink-connect", "jdbc:postgresql://localhost:5432/test",
            "--sink-table", "sink_table",
            "--sink-staging-table", "",  // Empty string
            "--mode", "incremental"
        };
        
        PostgresqlManager manager = createManagerWithMockConnection(args);
        
        // When: dropStagingTable is called
        manager.dropStagingTable();
        
        // Then: DROP statement SHOULD be executed (empty string is treated as not user-defined)
        verify(mockStatement, times(1)).executeUpdate(contains("DROP TABLE"));
        verify(mockConnection, times(1)).commit();
        
        LOG.info("✓ Empty staging table name is treated as auto-generated and dropped");
    }

    @Test
    void testDropStagingTable_userDefinedTable_logsSkipMessage() throws Exception {
        // Given: User explicitly defined staging table
        String[] args = {
            "--source-connect", "jdbc:postgresql://localhost:5432/test",
            "--source-table", "source_table",
            "--sink-connect", "jdbc:postgresql://localhost:5432/test",
            "--sink-table", "sink_table",
            "--sink-staging-table", "user_staging_table",
            "--mode", "incremental"
        };
        
        PostgresqlManager manager = createManagerWithMockConnection(args);
        
        // When: dropStagingTable is called (should return early)
        assertDoesNotThrow(() -> manager.dropStagingTable());
        
        // Then: Should complete without exceptions and without executing DROP
        verify(mockStatement, never()).executeUpdate(anyString());
        
        LOG.info("✓ Method returns gracefully when user-defined table is detected");
    }

    @Test
    void testCleanUp_withUserDefinedTable_respectsSafeguard() throws Exception {
        // Given: User defined staging table in incremental mode
        String[] args = {
            "--source-connect", "jdbc:postgresql://localhost:5432/test",
            "--source-table", "source_table",
            "--sink-connect", "jdbc:postgresql://localhost:5432/test",
            "--sink-table", "sink_table",
            "--sink-staging-table", "my_staging",
            "--mode", "incremental"
        };
        
        PostgresqlManager manager = createManagerWithMockConnection(args);
        
        // When: cleanUp is called (normal workflow)
        manager.cleanUp();
        
        // Then: Should not drop user-defined table
        verify(mockStatement, never()).executeUpdate(contains("DROP TABLE"));
        
        LOG.info("✓ cleanUp() respects user-defined staging table");
    }

    @Test
    void testDropStagingTable_sqlException_propagates() throws Exception {
        // Given: Auto-generated staging table, but DROP will fail
        String[] args = {
            "--source-connect", "jdbc:postgresql://localhost:5432/test",
            "--source-table", "source_table",
            "--sink-connect", "jdbc:postgresql://localhost:5432/test",
            "--sink-table", "sink_table",
            "--mode", "incremental"
        };
        
        PostgresqlManager manager = createManagerWithMockConnection(args);
        
        // Mock SQLException during DROP
        when(mockStatement.executeUpdate(anyString())).thenThrow(new SQLException("Table does not exist"));
        
        // When/Then: Exception should propagate
        assertThrows(SQLException.class, () -> manager.dropStagingTable());
        
        LOG.info("✓ SQL exceptions are properly propagated");
    }
}
