ALTER TABLE job_definition
    ALTER COLUMN source_table DROP NOT NULL,
    ADD COLUMN source_auth_mode VARCHAR(128),
    ADD COLUMN source_auth_principal_id TEXT,
    ADD COLUMN source_auth_login_hint TEXT,
    ADD COLUMN source_auth_client_certificate TEXT,
    ADD COLUMN source_auth_client_key TEXT,
    ADD COLUMN source_connection_params JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN source_columns TEXT,
    ADD COLUMN source_query TEXT,
    ADD COLUMN sink_auth_mode VARCHAR(128),
    ADD COLUMN sink_auth_principal_id TEXT,
    ADD COLUMN sink_auth_login_hint TEXT,
    ADD COLUMN sink_auth_client_certificate TEXT,
    ADD COLUMN sink_auth_client_key TEXT,
    ADD COLUMN sink_connection_params JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN sink_columns TEXT,
    ADD COLUMN sink_staging_schema TEXT,
    ADD COLUMN sink_staging_table TEXT,
    ADD COLUMN sink_disable_escape BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN sink_disable_truncate BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN fetch_size INTEGER NOT NULL DEFAULT 100 CHECK (fetch_size > 0),
    ADD COLUMN bandwidth_throttling INTEGER NOT NULL DEFAULT 0 CHECK (bandwidth_throttling >= 0),
    ADD COLUMN "verbose" BOOLEAN NOT NULL DEFAULT false;
