package org.replicadb;

import org.junit.jupiter.api.Test;
import org.replicadb.cli.ToolOptions;
import org.replicadb.execution.ReplicationCancelledException;
import org.replicadb.manager.ConnManager;
import org.replicadb.manager.DataSourceType;
import org.replicadb.manager.ManagerFactory;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ReplicaDBCancellationTest {

    @Test
    void returnsCancelledAndRunsCleanupForAnInFlightTask() throws Exception {
        ToolOptions options = options();
        RecordingManagerFactory managerFactory = new RecordingManagerFactory(options);
        assertEquals(ReplicaDB.CANCELLED, cancel(options, managerFactory));
        assertTrue(managerFactory.sink.cleanUpCalled);
    }

    @Test
    void dropsAutoGeneratedStagingTableWhenCancelled() throws Exception {
        ToolOptions options = options("incremental", null);
        RecordingManagerFactory managerFactory = new RecordingManagerFactory(options);

        assertEquals(ReplicaDB.CANCELLED, cancel(options, managerFactory));
        assertTrue(managerFactory.sink.stagingTableDropped);
    }

    @Test
    void preservesUserProvidedStagingTableWhenCancelled() throws Exception {
        ToolOptions options = options("incremental", "custom_staging");
        RecordingManagerFactory managerFactory = new RecordingManagerFactory(options);

        assertEquals(ReplicaDB.CANCELLED, cancel(options, managerFactory));
        assertTrue(managerFactory.sink.cleanUpCalled);
        assertFalse(managerFactory.sink.stagingTableDropped);
    }

    @Test
    void mapsAStatementCancellationSqlExceptionToCancelled() throws Exception {
        ToolOptions options = options("complete", null);
        RecordingManagerFactory managerFactory = new RecordingManagerFactory(options, true);

        assertEquals(ReplicaDB.CANCELLED, cancel(options, managerFactory));
        assertTrue(managerFactory.sink.cleanUpCalled);
    }

    private static int cancel(ToolOptions options, RecordingManagerFactory managerFactory) throws Exception {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        Future<Integer> result = executor.submit(() -> ReplicaDB.processReplica(options, managerFactory));

        try {
            assertTrue(managerFactory.sink.startedLatch.await(10, TimeUnit.SECONDS));
            options.getExecutionContext().requestCancellation();
            return result.get(10, TimeUnit.SECONDS);
        } finally {
            executor.shutdownNow();
            assertTrue(executor.awaitTermination(10, TimeUnit.SECONDS));
        }
    }

    private static ToolOptions options() throws Exception {
        return options("complete", null);
    }

    private static ToolOptions options(String mode, String stagingTable) throws Exception {
        String[] baseArgs = {
                "--mode", mode,
                "--source-connect", "jdbc:postgresql://source",
                "--source-table", "customers",
                "--sink-connect", "jdbc:postgresql://sink",
                "--sink-table", "customer_copy",
                "--jobs", "1"
        };
        if (stagingTable == null) {
            return new ToolOptions(baseArgs);
        }

        String[] args = java.util.Arrays.copyOf(baseArgs, baseArgs.length + 2);
        args[baseArgs.length] = "--sink-staging-table";
        args[baseArgs.length + 1] = stagingTable;
        return new ToolOptions(args);
    }

    private static final class RecordingManagerFactory extends ManagerFactory {
        private final RecordingManager source;
        private final RecordingManager sink;

        private RecordingManagerFactory(ToolOptions options) {
            this(options, false);
        }

        private RecordingManagerFactory(ToolOptions options, boolean throwSqlExceptionOnCancellation) {
            this.source = new RecordingManager(options, DataSourceType.SOURCE, null, false);
            this.sink = new RecordingManager(options, DataSourceType.SINK, new CountDownLatch(1),
                    throwSqlExceptionOnCancellation);
        }

        @Override
        public void validateAzureAuthenticationConfiguration(ToolOptions options) {
        }

        @Override
        public ConnManager accept(ToolOptions options, DataSourceType dataSourceType) {
            return DataSourceType.SOURCE.equals(dataSourceType) ? source : sink;
        }
    }

    private static final class RecordingManager extends ConnManager {
        private final CountDownLatch startedLatch;
        private final boolean throwSqlExceptionOnCancellation;
        private volatile boolean cleanUpCalled;
        private volatile boolean stagingTableDropped;

        private RecordingManager(ToolOptions options, DataSourceType dataSourceType, CountDownLatch startedLatch,
                                 boolean throwSqlExceptionOnCancellation) {
            this.options = options;
            this.startedLatch = startedLatch;
            this.throwSqlExceptionOnCancellation = throwSqlExceptionOnCancellation;
        }

        @Override
        public ResultSet readTable(String tableName, String[] columns, int nThread) {
            return null;
        }

        @Override
        public int insertDataToTable(ResultSet resultSet, int taskId) throws Exception {
            startedLatch.countDown();
            while (!options.getExecutionContext().isCancellationRequested()) {
                Thread.onSpinWait();
            }
            if (throwSqlExceptionOnCancellation) {
                throw new SQLException("driver reported statement cancellation");
            }
            throw new ReplicationCancelledException("test cancellation");
        }

        @Override
        public Connection getConnection() {
            return null;
        }

        @Override
        public String getDriverClass() {
            return "";
        }

        @Override
        public void close() {
        }

        @Override
        public void cleanUp() {
            cleanUpCalled = true;
            stagingTableDropped = options.getSinkStagingTable() == null
                    || options.getSinkStagingTable().isEmpty();
        }

        @Override
        public void release() {
        }

        @Override
        public void preSourceTasks() {
        }

        @Override
        public Future<Integer> preSinkTasks(ExecutorService executor) {
            return null;
        }

        @Override
        public void postSourceTasks() {
        }

        @Override
        public void postSinkTasks() {
        }

        @Override
        public String[] getSinkPrimaryKeys(String tableName) {
            return new String[0];
        }
    }
}