# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD ReplicaDB Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) " >> $GITHUB_ENV
 
 
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
        
    - name: Maven Install
      run: |
        export REPLICADB_RELEASE_VERSION=${{ env.version }}
        echo ${REPLICADB_RELEASE_VERSION}  
        mvn clean install -Dmaven.javadoc.skip=true -DskipTests -B -V -P release 
        cp ./target/ReplicaDB-*.jar . 
        mkdir lib
        echo ${REPLICADB_RELEASE_VERSION} 
        cp ./target/lib/* ./lib 
        tar -zcvf ReplicaDB-${REPLICADB_RELEASE_VERSION}.tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE
        zip -r -X ReplicaDB-${REPLICADB_RELEASE_VERSION}.zip ReplicaDB-*.jar README.md lib conf bin LICENSE
        ls -lah        

    - name: Maven Install no-oracle
      run: |
        export REPLICADB_RELEASE_VERSION=${{ env.version }}
        mvn clean install -Dmaven.javadoc.skip=true -DskipTests -B -V -P release-no-oracle
        cp ./target/ReplicaDB-*.jar . 
        rm -Rf lib 2>/dev/null
        mkdir lib        
        cp ./target/lib/* ./lib 
        tar -zcvf ReplicaDB-${REPLICADB_RELEASE_VERSION}-no-oracle.tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE
        zip -r -X ReplicaDB-${REPLICADB_RELEASE_VERSION}-no-oracle.zip ReplicaDB-*.jar README.md lib conf bin LICENSE
        ls -lah

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{ env.version }}
        prerelease: false
        files: |
          ReplicaDB-*.zip
          ReplicaDB-*.tar.gz

    -   name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
    -   name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
    -   name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    -   name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: osalvador/replicadb:${{ env.version }}, osalvador/replicadb:latest
          build-args: REPLICADB_RELEASE_VERSION=${{ env.version }}

    -   name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: osalvador/replicadb:ubi9-${{ env.version }}, osalvador/replicadb:ubi9-latest
          build-args: REPLICADB_RELEASE_VERSION=${{ env.version }}



    
