# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Only CI/CT JDK11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) " >> $GITHUB_ENV

    - name: Build and Integration Tests
      run: mvn -B package --file pom.xml

    - name: Clean Install
      run: |
        export REPLICADB_RELEASE_VERSION=${{ env.version }}
        echo ${REPLICADB_RELEASE_VERSION}  
        mvn clean install -Dmaven.javadoc.skip=true -DskipTests -B -V -P release 
        cp ./target/ReplicaDB-*.jar . 
        mkdir lib
        echo ${REPLICADB_RELEASE_VERSION} 
        cp ./target/lib/* ./lib 
        tar -zcvf ReplicaDB-v${REPLICADB_RELEASE_VERSION}.tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE 
        zip -r -X ReplicaDB-v${REPLICADB_RELEASE_VERSION}.zip ReplicaDB-*.jar README.md lib conf bin LICENSE 
        ls -lahtr

